version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # image: vit-events-api
    # container_name: vit-events-api
    command: yarn server
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
  webapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: vit-events-web-app
    # container_name: vit-events-web-app
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
